services:
  markdown-mermaid-pdf: &base
    build:
      context: .
    image: markdown-mermaid-pdf:latest
    volumes:
      - ./workspace:/workspace
    working_dir: /workspace

  markdown-mermaid-pdf-shell:
    <<: *base
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
